npm run precompile:token:ether:vyper
npm run compile:token:ether:vyper
npm run compile:token:ether:vyper:external
npm run precompile:token:market:vyper
npm run compile:token:market:vyper
npm run compile:token:market:vyper:external
npm run precompile:voting:vyper
npm run compile:voting:vyper
npm run compile:voting:vyper:external
npm run precompile:parameterizer:vyper
npm run compile:parameterizer:vyper
npm run compile:parameterizer:vyper:external
npm run precompile:reserve:vyper
npm run compile:reserve:vyper
npm run compile:reserve:vyper:external
npm run precompile:datatrust:vyper
npm run compile:datatrust:vyper
npm run compile:datatrust:vyper:external
npm run precompile:listing:vyper
npm run compile:listing:vyper
npm run compile:listing:vyper:external
